---
aws_region: ap-southeast-2
aws_zone: "{{ aws_region }}a"
vpc_cidr_block: "172.22.0.0/16"
key_name: "mqperf-key"
vpc_name: "mqperf-vpc"
subnet_cidr: "172.22.1.0/24"

s3_bucket: sml-mqperf

aws_access: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

mqperf_sources_dir: "{{ playbook_dir }}/.."

grafana_port: 3000
prometheus_port: 9090
rabbitmq_port: 15672
activemq_port: 8161
eventstore_port: 2113
activemq_artemis_jolokia_port: 8161
rocketmq_name_server_port: 9876
rocketmq_broker_port_main: 10909
rocketmq_broker_port_bkp_1: 10911
rocketmq_broker_port_bkp_2: 10912